### ISSUE TITLE
Question: static libs or dynamic libs

### ISSUE THREAD

**Issue by keiem** [bkacjios/RetroArch#2]
Dear bkacjios,

I'm trying to build some stuff for my pocketgo S30.  When running my builds on the pocketgo, i get the error message my libc lib version is to old.  

My question is if you build on a dedicted build environment or do you build with static libs.  Or is there another way to avoid the libc error?
I'm building on a recent armbian for allwinner H3.

**Comment by bkacjios** [comment]
I use the build environment that was provided by bittboy. This shouldn't cause any libc errors, since it's the same version they used to build the kernel and their libraries. I don't think they provide any static library files, so I use dynamic.

https://drive.google.com/file/d/1DT1TPZd79jQeNwelKxg8f096tPllSE4a/view

**Comment by keiem** [comment]
Thanks,

I searched for a official build environment from bittboy, but didn't find it.  Thanks for this, I will try it.
